<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Transfer RM46.82 Now</name>
   <tag></tag>
   <elementGuidId>709dc4d5-b66c-462d-8289-383a2812a632</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.vx_btn.vx_btn-large</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ccd1d537-a40a-49b4-85ea-2d8e8b1ebf70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vx_btn vx_btn-large</value>
      <webElementGuid>3dc99241-a527-4f38-83b8-630910efe67c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>96b72197-60af-4728-9b7b-7c7b3bfb35d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>d49fbe8b-4dce-4a8d-a3b8-4c6cfc664c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transfer RM 46.82 Now</value>
      <webElementGuid>cc381d59-420f-48d6-ab95-26c7b5c2fd37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vx_modal-wrapper&quot;)/div[1]/div[@class=&quot;vx_modal-content page-review push-enter-done&quot;]/div[@class=&quot;pageActions&quot;]/div[@class=&quot;actions&quot;]/button[@class=&quot;vx_btn vx_btn-large&quot;]</value>
      <webElementGuid>92b95dd7-c65f-4b51-aa69-875b5751c678</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>cdcec798-fca7-4234-8102-43b7bdf5905d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vx_modal-wrapper']/div/div/div[2]/div/button</value>
      <webElementGuid>2c6148f2-4f27-43e7-9ebc-31e7fc250815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RM 46.82'])[1]/following::button[1]</value>
      <webElementGuid>6190e4e5-9862-4229-b41c-671ce974e0df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('You', &quot;'&quot;, 'll get')])[1]/following::button[1]</value>
      <webElementGuid>91e98db6-7f84-4b58-a26d-db44a28363fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Transfer RM 46.82 Now']/parent::*</value>
      <webElementGuid>2781036d-fc9d-4bee-825b-65e3c1ddcc8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/button</value>
      <webElementGuid>7a52be5d-7952-4d39-8ba8-518635c8c045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Transfer RM 46.82 Now' or . = 'Transfer RM 46.82 Now')]</value>
      <webElementGuid>eebad4a1-a326-41b2-b660-c79573280021</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
