<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter transfer amount_amount</name>
   <tag></tag>
   <elementGuidId>750f12de-dd05-4cc0-aa98-9637cac36ae2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='amount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;amount&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b5f33c56-cd51-4edb-9308-fd9f5c799fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>83a6df0f-3dee-4251-8533-01efdc5a6c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>76f9d095-5ea0-4853-9638-6397b23b2886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>8d8ecf24-742f-4dc9-9366-18723a60715a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>amount</value>
      <webElementGuid>8eaa4f80-1bc5-4e74-83e5-20d7019c728c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ppaf-input</value>
      <webElementGuid>787ac0ff-a757-4d47-835b-4a4588c1dd7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>amountInputField</value>
      <webElementGuid>e2f5f0f0-fe75-4365-8b8d-c23efefa2c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Transfer amount</value>
      <webElementGuid>696d9c60-8008-4094-b9c2-0c8d7a86590b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4,990.44</value>
      <webElementGuid>b2fd10af-daa9-43c1-a832-49f78fcee467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vx_modal-wrapper&quot;)/div[1]/div[@class=&quot;vx_modal-content page-amount push-enter-done&quot;]/div[@class=&quot;amount-page&quot;]/div[@class=&quot;amount-container&quot;]/div[@class=&quot;amount-field-container&quot;]/div[@class=&quot;pp-amount-field basic-v1&quot;]/div[@class=&quot;ppaf-input-wrapper&quot;]/input[@class=&quot;ppaf-input&quot;]</value>
      <webElementGuid>e219887a-1663-48f1-b501-3070a520806b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='amount']</value>
      <webElementGuid>058ff5b2-0b87-494b-bf5d-428d64b4c9f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vx_modal-wrapper']/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>f7223d3a-0d6a-4ab0-8dd4-5cb43c03fd85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>01629a10-630c-4c10-a12d-a6cb0fa8eed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'amount']</value>
      <webElementGuid>c7f5484a-a2c1-44f7-9087-12b9fd4dd769</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
