<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Send</name>
   <tag></tag>
   <elementGuidId>516d0bc3-722f-4f4c-b979-8e48525a3dc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ppvx_btn___5-10-10-beta-0.ppvx_btn--size_sm___5-10-10-beta-0.primary-CTA</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fc4721b9-839a-4110-8217-d0aa2b9b8853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ppvx_btn___5-10-10-beta-0 ppvx_btn--size_sm___5-10-10-beta-0 primary-CTA</value>
      <webElementGuid>b2d89c3a-7966-448a-96b8-0a0a6db79eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>assertive</value>
      <webElementGuid>d1d1e0ea-013e-4a4d-9266-52210f562005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0aa76ef5-1e57-4032-b9f2-39c8fca339e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send</value>
      <webElementGuid>0c927b71-aea3-4a4a-9976-36ee9df1ccbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;invoicing-widget&quot;)/div[@class=&quot;vx_panel-tile css-1039kfj&quot;]/div[1]/form[1]/fieldset[1]/div[@class=&quot;row-mt-1 actions&quot;]/button[@class=&quot;ppvx_btn___5-10-10-beta-0 ppvx_btn--size_sm___5-10-10-beta-0 primary-CTA&quot;]</value>
      <webElementGuid>42fed695-66e8-47bb-b6b9-2d33435388b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>93db170a-58f6-4419-8b6d-795e3a301afb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='invoicing-widget']/div/div/form/fieldset/div[5]/button</value>
      <webElementGuid>fc774f5f-da96-4cef-aabb-6a8edbd7ceb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Currency'])[1]/following::button[1]</value>
      <webElementGuid>b4a8e36a-db6e-4ac4-b1f3-f4fbb58c218b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MYR'])[2]/following::button[1]</value>
      <webElementGuid>ff2eb332-64db-4be9-a584-0f922731c0b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Issue a refund'])[1]/preceding::button[1]</value>
      <webElementGuid>0f7dda61-bc59-4c0c-b1dc-7df1ece66dc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Send']/parent::*</value>
      <webElementGuid>10a704ed-6f46-4c5a-b5ff-6ecd55aaca3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button</value>
      <webElementGuid>5815d705-65f6-4036-9f9b-5c65ceb92006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Send' or . = 'Send')]</value>
      <webElementGuid>210ed530-1dd6-45a4-bdb7-57f5a5a02c43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
