<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Item name_itemAmount</name>
   <tag></tag>
   <elementGuidId>59cbab98-af11-4397-96f1-5dd671c14fcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='itemAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#itemAmount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5da9160f-6a3f-461c-b257-dfaf25af1fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ppvx_text-input__control___3-12-9 ppvx_text-input__control--prefix___3-12-9</value>
      <webElementGuid>a4d80bdc-e17a-419b-b380-6104d50342d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>itemAmount</value>
      <webElementGuid>e555f6b8-b6ab-4ab1-bfba-8fe1bd46db15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>itemAmount</value>
      <webElementGuid>c9ed4e0f-5f28-433d-aea9-14b208562762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5ee3cd61-022c-4e58-9159-5990bb062e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>itemAmount-label itemAmount-prefix</value>
      <webElementGuid>4235672f-b4cf-4cfa-9f71-1bd52e94df48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>fcaff40f-40c7-414d-aa79-dfce65d2a30c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itemAmount&quot;)</value>
      <webElementGuid>c7ace4b9-5ca4-4fdc-be25-5e9fce569dc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='itemAmount']</value>
      <webElementGuid>cac062d7-8975-4c54-8bf5-44dd902bab82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='invoicing-widget']/div/div/form/fieldset/div[4]/div/div/div/input</value>
      <webElementGuid>0122db1a-f86a-4f51-bc54-8e02af41689f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>3261f43d-3977-419c-bf46-3ebaacc34952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'itemAmount' and @id = 'itemAmount']</value>
      <webElementGuid>8750b819-669c-4321-987a-6f4b3bbd9464</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
