<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Log Masuk</name>
   <tag></tag>
   <elementGuidId>4aaaf0c1-9167-4d36-871f-b59c8d898d76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ul-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ul-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4a11e168-f200-412a-a207-d957ae7dbf55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ul-btn</value>
      <webElementGuid>cff68f24-5b33-4783-a332-308ce9df473d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.sandbox.paypal.com/signin</value>
      <webElementGuid>01b75678-4750-4283-96a9-56d93ef5f31a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pypl-btn mpp-btn pypl-btn--outline-white pypl-btn--small</value>
      <webElementGuid>e246d69a-5a32-4d08-bb54-11b908c5e5ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pa-click</name>
      <type>Main</type>
      <value>{&quot;link&quot;: &quot;HeaderMainMenu0-Cta-Log Masuk&quot;,&quot;event_name&quot;:&quot;ppcom_header_login_clicked&quot;}</value>
      <webElementGuid>d6b65e20-bef9-4a02-9a65-be95a6aa4a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>f82ab9b0-8bc9-4bbc-957b-49a8c2783388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0e91fb15-df78-4d25-89a8-e027007090d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log Masuk</value>
      <webElementGuid>8891a62a-9d5f-4dc5-84d4-1444af6354b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ul-btn&quot;)</value>
      <webElementGuid>9a1801ad-32db-4d8f-b590-e90c188780b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ul-btn']</value>
      <webElementGuid>210c00c8-dafe-4f49-8858-15a63d9f695c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-buttons']/div/a</value>
      <webElementGuid>38523e38-3160-4b0f-9512-6abbc55b77fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Log Masuk')]</value>
      <webElementGuid>c6de68e4-dac6-4725-bbfe-27f95ab23827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar secara Percuma'])[1]/following::a[1]</value>
      <webElementGuid>4c359674-ee83-445d-b8eb-3513a68210fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cegah penipuan dalam talian'])[1]/following::a[3]</value>
      <webElementGuid>568b55df-f685-4ef1-b924-cea896ea2aed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/preceding::a[1]</value>
      <webElementGuid>3ee8a5b2-e841-4abf-86d4-ff9e7ac6c6ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Sales'])[1]/preceding::a[3]</value>
      <webElementGuid>d8495175-7445-4208-8f2d-b17ea92a2a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Log Masuk']/parent::*</value>
      <webElementGuid>e9b49276-f8fa-426e-ad7b-a79ce0cb7fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.sandbox.paypal.com/signin')]</value>
      <webElementGuid>f65e6761-d9dc-438a-9304-4e138594ffaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
      <webElementGuid>ddfe7006-cbbe-4be1-94c0-d5c67ddb4195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ul-btn' and @href = 'https://www.sandbox.paypal.com/signin' and (text() = 'Log Masuk' or . = 'Log Masuk')]</value>
      <webElementGuid>4896a0d5-867e-4882-8ce3-2bf627b9291b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
