<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Total received</name>
   <tag></tag>
   <elementGuidId>d9ccdcc0-a0fe-4d7a-9e0e-1f6425ba33bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='moneyIn']/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.balance-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>89cea32f-2472-4747-ba99-d1384ee069fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6f961aaf-3778-40f1-a197-cf14669ac063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ed9b35f2-5015-417e-9dec-d133f1be05cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>balance-label</value>
      <webElementGuid>bca3aeca-9edd-4676-8187-699c155d55c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Total received</value>
      <webElementGuid>445a79d8-1d5b-4fbe-927e-b897613cc0c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;moneyIn&quot;)/div[@class=&quot;vx_panel-tile tile-wrapper&quot;]/div[@class=&quot;balance-label&quot;]</value>
      <webElementGuid>b17e96c8-56d9-4917-bb04-eb25d4d854f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='moneyIn']/div/div[3]</value>
      <webElementGuid>e3f8db7f-c6da-4eab-99c1-73c18657ba47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Money in'])[1]/following::div[2]</value>
      <webElementGuid>e6d2dc7e-0f23-477b-adcb-cdf11898685f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last 90 days'])[1]/following::div[5]</value>
      <webElementGuid>ec5fb484-ded9-4ec4-bf0a-8f4e57872df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total sent or spent'])[1]/preceding::div[5]</value>
      <webElementGuid>3baf96bc-4ef0-4607-90fa-ff7245f195ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick links'])[1]/preceding::div[9]</value>
      <webElementGuid>81ec81c9-f7ce-4177-9851-b4e42d668bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Total received']/parent::*</value>
      <webElementGuid>09226b00-f62d-455c-9285-ef8e1fd26538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div/div[2]/div/div[3]</value>
      <webElementGuid>32af9bc5-39a8-4b3c-aca6-8408e4c13769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Total received' or . = 'Total received')]</value>
      <webElementGuid>e7327a26-7668-44cf-a27a-361ab58525e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
