<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div</name>
   <tag></tag>
   <elementGuidId>3392b104-bf27-46b4-bfab-cb6f3595eda3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='merchant-header-main-wrapper-internal']/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>73e9c8fa-4ef2-4c5a-a945-94816f512639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;merchant-header-main-wrapper-internal&quot;)/div[1]/div[2]/div[1]</value>
      <webElementGuid>aafe66a9-beaf-40ad-a9ff-2330b430eba6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='merchant-header-main-wrapper-internal']/div/div[2]/div</value>
      <webElementGuid>ee5fe45f-42ea-4f4f-bf81-94069361f7f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div</value>
      <webElementGuid>95d62c72-0dab-40d5-b61c-c50341c6cb8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
